name: Unit test

on:
  - push
  - pull_request

env:
  COMPOSER_FLAGS: "--ansi --no-interaction --no-progress --prefer-dist"

jobs:
    tests:
        name: "PhpUnit"
        runs-on: ubuntu-latest
        continue-on-error: ${{ matrix.experimental }}
        strategy:
            fail-fast: false
            matrix:
                php-version:
                    - "8.0"
                    - "8.1"
                    - "8.2"
                    - "8.3"
                experimental:
                    - false
                include:
                    - php-version: "8.4"
                      composer-options: "--ignore-platform-reqs"
                      experimental: true

        steps:
            - name: "Install PHP"
              uses: "shivammathur/setup-php@v2"
              with:
                coverage: "none"
                php-version: "${{ matrix.php-version }}"

            - name: "Checkout"
              uses: "actions/checkout@v4"

            - name: Get composer cache directory
              id: composer-cache
              run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

            - name: Cache dependencies
              uses: actions/cache@v3
              with:
                path: ${{ steps.composer-cache.outputs.dir }}
                key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
                restore-keys: ${{ runner.os }}-composer-

            - name: "Install latest dependencies"
              run: "composer update ${{ env.COMPOSER_FLAGS }} ${{ matrix.composer-options }}"

            - name: "Run tests"
              run: ./vendor/bin/phpunit -c phpunit.xml.dist
